name: build and test

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '23.0.1'
          distribution: 'graalvm'
          architecture: x64
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.12'

      - name: Build and test
        run: make test

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ./app/src/main/java
        with:
          coverageCommand: make test-report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco